---
dependencies:
        - role: nginx
          vars:
                  todoapp_port: "{{ todoapp_port }}"
                  todoapp_path: "{{ todoapp_path }}"
        - role: nodejs
          vars:
                  todoapp_path: "{{ todoapp_path }}"
        - role: mongodb
          vars:
                  mongo_instance_name: "{{ mongo_instance_name }}"
        - role: todoapp_service
          vars:
                  todoapp_port: "{{ todoapp_port }}"
                  todoapp_path: "{{ todoapp_path }}"
                  todoapp_user: "{{ todoapp_user }}"

